# Generated by Django 5.0.6 on 2024-08-16 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='user',
        ),
        migrations.AddField(
            model_name='route',
            name='vehicle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.vehicle'),
            preserve_default=False,
        ),
    ]
