# Generated by Django 5.0.6 on 2024-07-31 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='order',
            field=models.CharField(max_length=100),
        ),
    ]
