# Generated by Django 5.0.6 on 2024-08-16 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_route_user_route_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='home.vehicle'),
        ),
    ]
