# Generated by Django 5.0.6 on 2024-06-05 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_address_latitude_address_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
