# Generated by Django 5.0.6 on 2024-08-01 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_route_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='brand',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='model',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='plate',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='latitude',
            field=models.CharField(default='0.0', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='longitude',
            field=models.CharField(default='0.0', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='origin_address',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
