# Generated by Django 5.0.6 on 2024-08-16 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_route_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.vehicle'),
        ),
    ]
