# Generated by Django 5.0.6 on 2024-06-05 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_route_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='capacity',
            field=models.IntegerField(default=1),
        ),
    ]
