# Generated by Django 5.0.6 on 2024-08-01 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_brand_vehicle_name_remove_vehicle_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='driver',
        ),
        migrations.AddField(
            model_name='route',
            name='vehicle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='home.vehicle'),
            preserve_default=False,
        ),
    ]
