# Generated by Django 5.0.6 on 2024-06-13 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_vehicle_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
