# Generated by Django 5.0.6 on 2024-08-20 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_route_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routeaddress',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='routeaddress',
            name='alert_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='routeaddress',
            name='delivery_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='routeaddress',
            name='departure_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='routeaddress',
            name='estimated_arrival_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='routeaddress',
            name='note',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='routeaddress',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='route_photos/'),
        ),
        migrations.AddField(
            model_name='routeaddress',
            name='recipient_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='routeaddress',
            name='recipient_signature',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='signatures/'),
        ),
        migrations.AddField(
            model_name='routeaddress',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='routeaddress',
            name='time_window_end',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='routeaddress',
            name='time_window_start',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
