# Generated by Django 5.0.6 on 2024-07-08 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_route_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='driver',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='home.vehicle'),
        ),
        migrations.AlterField(
            model_name='route',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='home.address'),
        ),
        migrations.AlterField(
            model_name='route',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='home.driver'),
        ),
        migrations.AlterField(
            model_name='route',
            name='parent_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='home.parentitem'),
        ),
        migrations.AddField(
            model_name='address',
            name='company',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='home.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='company',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='home.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parentitem',
            name='company',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='parent_items', to='home.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='company',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='upload_files', to='home.company'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fleets', to='home.company')),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fleet',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='home.fleet'),
            preserve_default=False,
        ),
    ]
